Реализованы все требования ТЗ. Добавлены комментарии. Checkstyle от Sun
aigunov/java-shareit pull request #1
Opened 2024-07-19 07:29 UTC by aigunov

Добрый день.  Реализовал тз отправляю на проверку.
У меня есть просьба. Можете оценивать код строже? Просто я понимаю что мой код далеко не хорош, но самому это понять без сторонних замечаний очень тяжело, так что попрошу оставлять комментарии во всех местах где можно улучшить или исправить код. Также можете кидать больше ссылок на ресурсы для обучения?

2024-07-20 07:32 UTC, YazykovMikhail requested changes

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * POJO Booking
Удаляй лишние комментарии, ты уже реализовал этот функционал, комметарий уже не нужен
Поправь везде

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * POJO Booking
Хотя Booking для этого задания реаоизовывать не нужно было

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Request request;
Этот функционал еще не реализован, стоит убрать лишние поле

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = userService.addUser(userDto);
Необходимо логирование входных данных, иначе как потом понять что пришло в запросе?

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = userService.addUser(userDto);
Поправь везде

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public User addUser(final UserDtoToCreate userDtoToCreate) {
Возвращать стоит тоже dto, не стоит возвращать Модель которая хранится в хранилище, даже есдт эти даные одинаковы
ПОправь везде

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@Valid @RequestBody final UserDtoToCreate userDto) {
Молодец что делаешь dto, луше их называть например:
UserCreateRequest - для зпроса
UserCreateResponse - для ответа
Если везде будет общий ответ, можно сделать общее дто для ответа
UserResponse

Аналогично для других контроллеров/эндпоинтов

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +    private Long counter = 1L;
Стоит начинать с 0
а когда делаешь установку делать:
++counter

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +    private final List<User> users;
Лучше хранить в структуре HashMap что бы можно было быстро/легко получать обьекты

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +    private final List<User> users;
Поправь и для Item

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +    public User updateUser(final UserDtoToUpdate userDto, final long userId) {
В слой хранилища dto приходить не должно, уже готовые обьет для сохранения, т.е сами модели
id отдельно передавать не нужно, оно уже будет в User

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +        user.setName(userDto.getName() != null ? userDto.getName() : user.getName());
Как ты уже понял это лишнее, данные уже приходят сюда готовые.
Да и таого не может быть, что бы пришли null ведь у тебя стоит валидация на этих полях и это верно

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +
Стоит сделать отдельное поле для хранения емейлов
	private final Set<String> emailUniqSet = new HashSet<>();
Это будет как индекс в БазахДанных (в будущем пройдешь), он нужен для валидации уникальности емейлов

Вот например как с ним может выглядеть метод добавления:
```
public User save(User user) {
		final String email = user.getEmail();
		if (emailUniqSet.contains(email)) {
			throw new DataAlreadyExistException("Email: " + email + " already exists");
		}
		user.setId(++counter);
		storage.put(user.getId(), user);
		emailUniqSet.add(email);
		return user;
	}

```

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +
Аналогично адаптируй для обновления

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        userDAO.getAllUsers().stream().forEach(user -> {
Показал как лучше реализовать в ДАО

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/utils/BookingStatus.java
> +package ru.practicum.shareit.utils;
ENUM это такая же сущность как и сам обьект, это не утилита, вынеси в bokking.model

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/utils/BookingStatus.java
> +package ru.practicum.shareit.utils;
Но опять же Booking еще реализовывать не нужно

2024-07-20 07:32 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/utils/Mapper.java
> +public final class Mapper {
Мапер тоже должен быть у кждого свой, у каждой модели свой маппер.
Поэтому вынеси в соотвествующие пакеты
и создай там папку mapper

2024-07-20 11:02 UTC, aigunov commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +        user.setName(userDto.getName() != null ? userDto.getName() : user.getName());
в том то и дело что может быть
в тестах на update отправляется ответ с одним-двумя полями
то есть мне нужно чтобы на дто к обновлению не было валидации 
и мне надо проверять не null ли какое-то поле в переданном для обновления теле 
поэтому мне надо передавать в дао именно userdtoupdate как и с itemdtoupdate

2024-07-20 11:09 UTC, aigunov commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +        user.setName(userDto.getName() != null ? userDto.getName() : user.getName());
если я для userdao и itemdao буду отправлять в методы update именно модели(item, user) то мне придется убирать валидацию с них потому что как я и сказал в тестах есть запросы update где только одно поле а все остальные не переданы

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDtoResponse addUser(@Valid @RequestBody final UserDtoCreate userDto) {
Dto в названии не обязаткльно и так понятно что это dto

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDtoResponse updateUser(@PathVariable final Long userId, @RequestBody final UserDtoUpdate userDto) {
Валидация на обязательные поля должна быть внутри  UserDtoUpdate
и сответсвенно тут @Valid

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotEmpty
Тут эти аннотации не нужны, валидация иет на урвоне контроллеров и когда в добавок есть аннотация @Valid
Модель не участвует в контроллере, она собирается из входящих даных которые уже проверены

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
Вот тут стоит сдеать метод маппра который делает из 
userDtoUpdate и userId
готовую модель User и уже она отправляется в dao

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDtoResponse addUser(@Valid @RequestBody final UserDtoCreate userDto) {
Обрати внимание, тут у тебя есть валидация входящих данных
@Valid @RequestBody final UserDtoCreate 
но почему на обновлении нет? Там же тоже нужно проверять валидность данных и обязательные должны приходить все

2024-07-20 15:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +        user.setName(userDto.getName() != null ? userDto.getName() : user.getName());
В дао передается только Модели, это в любом случае, дто заканчиваются на уровне сервиса. 
Валидация должна проходить в UserDtoUpdate на увроне контроллера и с помощью аннотаций, аналогично методу create

2024-07-20 15:39 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserDAOImpl.java
> +        user.setName(userDto.getName() != null ? userDto.getName() : user.getName());
Хах, сейчас посмотрел и прав есть такой тест, ведь это метод Path а не Post/Put. 
Но в любому случае в дао/репозиторий/хранилище приходят только модели, они должны быт ьуже подготовленные заранее.
Если валидацию невозможно сделать на уровне контролера, она переносится на увроень сервиса, тем более там будет необходимо часть перемнных заменять, поэтому вынеси эту логику в сервис.
Важный момент: слой приложения отвечающий за хранения данных принимает/возвращает только Модели

2024-07-20 15:43 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        UserDtoResponse user = UserMapper.toUserDto(userDAO.updateUser(userDtoUpdate, userId));
Старайся не делать все в одну строки, получается каша

2024-07-20 15:43 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
И потом сдлеать проверку для полей по принципу обновления Path
что то типо такого:
		```
final User newUser = UserMapper.toUser(userDto);

		final User user = userRepository.findById(newUser.getId());
		if (user == null) {
			throw new NotFoundException("User with id=" + newUser.getId() + " not found");
		}

		if (newUser.getName() == null) {
			newUser.setName(user.getName());
		}
		if (newUser.getEmail() == null) {
			newUser.setEmail(user.getEmail());
		}
		User updatedUser = userRepository.update(newUser);
                return UserMapper.toUser(updatedUser);
```

2024-07-20 15:49 UTC, YazykovMikhail reviewed
Комментарии для User аналогичны и для Item

2024-07-20 15:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDtoResponse toItemDto(final Item item) {
toItemResponse - должно быть понятно в какое дто возвращает

2024-07-20 15:50 UTC, YazykovMikhail requested changes
Комментарии выше

2024-07-20 15:53 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
И потом проверку полей для типа обновления Path, как то так получится:

```
	public UserDto updateUser(UserDto userDto) {
		final User newUser = UserMapper.toUser(userDto);

		final User user = userRepository.findById(newUser.getId());
		if (user == null) {
			throw new NotFoundException("User with id=" + newUser.getId() + " not found");
		}

		if (newUser.getName() == null) {
			newUser.setName(user.getName());
		}
		if (newUser.getEmail() == null) {
			newUser.setEmail(user.getEmail());
		}
		User updatedUser = userRepository.update(newUser);
                return UserMapper.toUser(updatedUser);
```

2024-07-20 15:56 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +
Подсвечу тут, слои приложения которые отвечают за общение с хранилищем (дао, репозиторий, хранилище) принимают и возвращают только Модели которые храняться в этом хранилище

2024-07-20 19:12 UTC, aigunov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        UserDtoResponse user = UserMapper.toUserDto(userDAO.updateUser(userDtoUpdate, userId));
это не я 
просто рефакторинг ctr+alt+l проекта сам это переносит

2024-07-21 04:02 UTC, YazykovMikhail approved these changes

2024-07-21 08:07 UTC, merged